spring:
  application:
    name: spring-boot-temporal

  temporal:
    connection:
      enable-https: false
      target: "localhost:7233"
    namespace: greeting
    workers-auto-discovery:
      packages:
        - com.example.spring_temporal.temporal.worker

server:
  port: 9000

app:
  temporal:
    task-queue: "greeting-queue"