spring:
  application:
    name: spring-boot-temporal

  temporal:
    connection:
      enable-https: false
      target: "localhost:7233"
    namespaces:
      - namespace: greeting
        alias: greeting
        workers-auto-discovery:
          packages:
            - com.example.spring_temporal.temporal.greeting
      - namespace: farewell
        alias: farewell
        workers-auto-discovery:
          packages:
            - com.example.spring_temporal.temporal.farewell


server:
  port: 9000

app:
  temporal:
    greeting-task-queue: "greeting-queue"
    farewell-task-queue: "farewell-queue"
