server:
  port: 9000

app:
  temporal:
    migration-queue: "migration-queue"

spring:
  application:
    name: spring-boot-temporal

  temporal:
    connection:
      enable-https: false
      target: "localhost:7233"
    workers-auto-discovery:
      packages: com.example.spring_temporal